services:
  db:
    container_name: bookstore-db
    image: mysql:latest
    restart: always
    ports:
      - 33060:3306
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
    logging:
      options:
        mode: non-blocking
        max-buffer-size: 1K
  api:
    container_name: bookstore-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    ports:
      - 50000:5000
    volumes:
      - .:/bookstore
    env_file:
      - ./.env
    logging:
      options:
        mode: non-blocking
        max-buffer-size: 1K
    depends_on:
      db:
        condition: service_healthy
    entrypoint: [ "python3", "-m", "flask", "run", "--host", "0.0.0.0", "--port", "5000"]
